import type { ReactNode } from 'react';
import {
  ApartmentOutlined,
  AuditOutlined,
  BankOutlined,
  DashboardOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  SafetyCertificateOutlined,
  SearchOutlined,
} from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { matchPath } from 'react-router-dom';

export interface NavigationChild {
  key: string;
  label: string;
  path: string;
}

export interface NavigationSection {
  key: string;
  label: string;
  path: string;
  icon: ReactNode;
  description: string;
  children?: NavigationChild[];
}

export interface AppRouteMeta {
  key: string;
  path: string;
  title: string;
  breadcrumb: string;
  description: string;
  sectionKey: string;
  sectionLabel: string;
  activeMenuKey: string;
  kind: 'home' | 'placeholder';
  features: string[];
}

type MenuItem = Required<MenuProps>['items'][number];

export const primaryNavigation: NavigationSection[] = [
  {
    key: 'home',
    label: '首页',
    path: '/home',
    icon: <DashboardOutlined />,
    description: '平台概览、演示数据和快捷入口。',
  },
  {
    key: 'regulations',
    label: '国内法规智库',
    path: '/regulations',
    icon: <BankOutlined />,
    description: '国内法规、地方负面清单、法规问答和比较分析。',
    children: [
      { key: 'regulations-home', label: '法规智库首页', path: '/regulations' },
      { key: 'regulations-qa', label: '智能法规问答', path: '/regulations/qa' },
      { key: 'regulations-compare', label: '法规比较', path: '/regulations/compare' },
    ],
  },
  {
    key: 'assessment',
    label: '合规研判',
    path: '/assessment',
    icon: <AuditOutlined />,
    description: '汽车数据分类、合规路径研判、政策识别和结果留痕。',
    children: [
      { key: 'assessment-home', label: '合规研判首页', path: '/assessment' },
      { key: 'assessment-path', label: '跨境合规研判', path: '/assessment/path' },
      { key: 'assessment-list-policy', label: '清单政策识别', path: '/assessment/list-policy' },
      { key: 'assessment-history', label: '研判记录', path: '/assessment/history' },
    ],
  },
  {
    key: 'governance',
    label: '数据治理与评估',
    path: '/governance',
    icon: <ApartmentOutlined />,
    description: '汽车数据资产、分类分级、重要数据识别与国内法规联动。',
    children: [
      { key: 'governance-home', label: '治理首页', path: '/governance' },
      { key: 'governance-assets', label: '数据资产清单', path: '/governance/assets' },
      { key: 'governance-classification', label: '分类分级', path: '/governance/classification' },
      { key: 'governance-important-data', label: '重要数据识别', path: '/governance/important-data' },
    ],
  },
  {
    key: 'filing',
    label: '申报备案',
    path: '/filing',
    icon: <FileProtectOutlined />,
    description: '安全评估、标准合同、认证材料和检查流程。',
    children: [
      { key: 'filing-home', label: '申报备案首页', path: '/filing' },
      { key: 'filing-security-assessment', label: '安全评估申报', path: '/filing/security-assessment' },
      { key: 'filing-standard-contract', label: '标准合同备案', path: '/filing/standard-contract' },
      { key: 'filing-certification', label: '个人信息保护认证', path: '/filing/certification' },
      { key: 'filing-materials', label: '材料中心', path: '/filing/materials' },
      { key: 'filing-material-check', label: '材料完整性检查', path: '/filing/material-check' },
      { key: 'filing-history', label: '办理记录', path: '/filing/history' },
    ],
  },
  {
    key: 'security',
    label: '安全流通',
    path: '/security',
    icon: <SafetyCertificateOutlined />,
    description: '技术方案、传输方案、监测视图和审计能力。',
    children: [
      { key: 'security-home', label: '安全流通首页', path: '/security' },
      { key: 'security-solution', label: '技术方案', path: '/security/solution' },
      { key: 'security-transfer', label: '跨境传输方案', path: '/security/transfer' },
      { key: 'security-monitor', label: '安全监测', path: '/security/monitor' },
      { key: 'security-audit', label: '审计日志', path: '/security/audit' },
      { key: 'security-trusted-space', label: '可信数据空间', path: '/security/trusted-space' },
    ],
  },
  {
    key: 'reports',
    label: '报告中心',
    path: '/reports',
    icon: <FileTextOutlined />,
    description: '统一查看各类报告和导出入口。',
  },
];

export const routeCatalog: AppRouteMeta[] = [
  {
    key: 'home',
    path: '/home',
    title: '首页工作台',
    breadcrumb: '首页',
    description: '展示平台概览、核心模块入口、演示统计和快捷操作。',
    sectionKey: 'home',
    sectionLabel: '首页',
    activeMenuKey: 'home',
    kind: 'home',
    features: ['平台概览', '核心模块入口', '演示统计'],
  },
  {
    key: 'search',
    path: '/search',
    title: '全局搜索',
    breadcrumb: '全局搜索',
    description: '统一搜索法规、国家画像、报告、数据资产、材料和服务机构。',
    sectionKey: 'home',
    sectionLabel: '公共页面',
    activeMenuKey: 'home',
    kind: 'placeholder',
    features: ['法规搜索', '数据资产搜索', '服务机构搜索'],
  },
  {
    key: 'reports',
    path: '/reports',
    title: '报告中心',
    breadcrumb: '报告中心',
    description: '集中查看研发设计、生产制造、自动驾驶、软件升级、联网运行和售后诊断报告。',
    sectionKey: 'reports',
    sectionLabel: '报告中心',
    activeMenuKey: 'reports',
    kind: 'placeholder',
    features: ['汽车场景筛选', '报告预览', '导出报告'],
  },
  {
    key: 'reports-detail',
    path: '/reports/:id',
    title: '报告详情',
    breadcrumb: '报告详情',
    description: '展示报告摘要、章节预览、相关法规和导出操作。',
    sectionKey: 'reports',
    sectionLabel: '报告中心',
    activeMenuKey: 'reports',
    kind: 'placeholder',
    features: ['文档预览', '相关法规', '导出报告'],
  },
  {
    key: 'settings',
    path: '/settings',
    title: '系统设置',
    breadcrumb: '系统设置',
    description: '管理环境偏好、最近访问记录、存储概览和一键清理。',
    sectionKey: 'settings',
    sectionLabel: '系统设置',
    activeMenuKey: 'settings',
    kind: 'placeholder',
    features: ['主题模式', '访问记录', '清除环境数据'],
  },
  {
    key: 'regulations-home',
    path: '/regulations',
    title: '国内法规智库首页',
    breadcrumb: '国内法规智库',
    description: '聚合国家层面法规、地方负面清单、重点主题、最新更新和快捷入口。',
    sectionKey: 'regulations',
    sectionLabel: '国内法规智库',
    activeMenuKey: 'regulations-home',
    kind: 'placeholder',
    features: ['国家层面法规', '地方负面清单', '热门问题'],
  },
  {
    key: 'regulations-library',
    path: '/regulations/library',
    title: '国内法规智库',
    breadcrumb: '国内法规智库',
    description: '旧入口已合并至国内法规智库首页。',
    sectionKey: 'regulations',
    sectionLabel: '国内法规智库',
    activeMenuKey: 'regulations-home',
    kind: 'placeholder',
    features: ['国家层面法规', '地方负面清单', '热门问题'],
  },
  {
    key: 'regulations-detail',
    path: '/regulations/detail/:id',
    title: '法规详情页',
    breadcrumb: '法规详情',
    description: '支持条款目录、原文切换、重点条款标记、相关法规和历史版本展示。',
    sectionKey: 'regulations',
    sectionLabel: '国内法规智库',
    activeMenuKey: 'regulations-home',
    kind: 'placeholder',
    features: ['条款目录', '原文与译文', '相关法规'],
  },
  {
    key: 'regulations-country',
    path: '/regulations/country',
    title: '国内法规智库',
    breadcrumb: '国内法规智库',
    description: '旧入口已合并至国内法规智库首页。',
    sectionKey: 'regulations',
    sectionLabel: '国内法规智库',
    activeMenuKey: 'regulations-home',
    kind: 'placeholder',
    features: ['国家层面法规', '地方负面清单', '热门问题'],
  },
  {
    key: 'regulations-qa',
    path: '/regulations/qa',
    title: '智能法规问答',
    breadcrumb: '智能法规问答',
    description: '使用知识规则和预置答案实现法规问答与条款引用。',
    sectionKey: 'regulations',
    sectionLabel: '国内法规智库',
    activeMenuKey: 'regulations-qa',
    kind: 'placeholder',
    features: ['对话区域', '推荐问题', '法规引用'],
  },
  {
    key: 'regulations-compare',
    path: '/regulations/compare',
    title: '法规比较页',
    breadcrumb: '法规比较',
    description: '支持多国家主题差异对比、差异摘要和结果导出。',
    sectionKey: 'regulations',
    sectionLabel: '国内法规智库',
    activeMenuKey: 'regulations-compare',
    kind: 'placeholder',
    features: ['多国家选择', '差异摘要', '对比表格'],
  },
  {
    key: 'assessment-home',
    path: '/assessment',
    title: '合规研判首页',
    breadcrumb: '合规研判',
    description: '聚合跨境合规研判、政策识别、最近记录和研判报告入口。',
    sectionKey: 'assessment',
    sectionLabel: '合规研判',
    activeMenuKey: 'assessment-home',
    kind: 'placeholder',
    features: ['统一研判入口', '最近记录', '汽车场景'],
  },
  {
    key: 'assessment-precheck',
    path: '/assessment/precheck',
    title: '跨境合规研判',
    breadcrumb: '跨境合规研判',
    description: '旧版预检入口，自动转入统一跨境合规研判流程。',
    sectionKey: 'assessment',
    sectionLabel: '合规研判',
    activeMenuKey: 'assessment-path',
    kind: 'placeholder',
    features: ['统一研判入口'],
  },
  {
    key: 'assessment-path',
    path: '/assessment/path',
    title: '跨境合规研判',
    breadcrumb: '跨境合规研判',
    description: '基于汽车场景、数据类别和数量区间生成合规路径与安全评估建议。',
    sectionKey: 'assessment',
    sectionLabel: '合规研判',
    activeMenuKey: 'assessment-path',
    kind: 'placeholder',
    features: ['汽车场景', '数据分类', '数量门槛', '报告生成'],
  },
  {
    key: 'assessment-list-policy',
    path: '/assessment/list-policy',
    title: '清单政策识别',
    breadcrumb: '清单政策识别',
    description: '识别负面清单、豁免条件、自贸区便利化政策和绿色通道线索。',
    sectionKey: 'assessment',
    sectionLabel: '合规研判',
    activeMenuKey: 'assessment-list-policy',
    kind: 'placeholder',
    features: ['负面清单', '豁免条件', '绿色通道'],
  },
  {
    key: 'assessment-result',
    path: '/assessment/result/:id',
    title: '研判结果页',
    breadcrumb: '研判结果',
    description: '展示推荐路径、规则路径图、法规依据以及报告生成操作。',
    sectionKey: 'assessment',
    sectionLabel: '合规研判',
    activeMenuKey: 'assessment-path',
    kind: 'placeholder',
    features: ['推荐路径', '待确认事项', '法规依据'],
  },
  {
    key: 'assessment-history',
    path: '/assessment/history',
    title: '研判记录页',
    breadcrumb: '研判记录',
    description: '支持筛选、查看结果、复制为新研判和删除记录。',
    sectionKey: 'assessment',
    sectionLabel: '合规研判',
    activeMenuKey: 'assessment-history',
    kind: 'placeholder',
    features: ['记录列表', '状态筛选', '复制为新研判'],
  },
  {
    key: 'governance-home',
    path: '/governance',
    title: '数据治理与评估首页',
    breadcrumb: '数据治理与评估',
    description: '聚合汽车数据资产、分类分级、重要数据识别和国内法规联动入口。',
    sectionKey: 'governance',
    sectionLabel: '数据治理与评估',
    activeMenuKey: 'governance-home',
    kind: 'placeholder',
    features: ['资产数量', '分类分级', '重要数据识别', '法规支撑'],
  },
  {
    key: 'governance-assets',
    path: '/governance/assets',
    title: '数据资产清单',
    breadcrumb: '数据资产清单',
    description: '支持按分类、目的地、风险等级筛选资产，并查看资产详情。',
    sectionKey: 'governance',
    sectionLabel: '数据治理与评估',
    activeMenuKey: 'governance-assets',
    kind: 'placeholder',
    features: ['资产表格', '批量导入', '导出模板'],
  },
  {
    key: 'governance-asset-detail',
    path: '/governance/assets/:id',
    title: '数据资产详情',
    breadcrumb: '数据资产详情',
    description: '展示资产字段示例、流向路径、控制措施、相关评估与治理说明。',
    sectionKey: 'governance',
    sectionLabel: '数据治理与评估',
    activeMenuKey: 'governance-assets',
    kind: 'placeholder',
    features: ['基本信息', '数据字段', '评估记录'],
  },
  {
    key: 'governance-classification',
    path: '/governance/classification',
    title: '分类分级页',
    breadcrumb: '分类分级',
    description: '展示分级统计、分类分布和待人工复核资产样例。',
    sectionKey: 'governance',
    sectionLabel: '数据治理与评估',
    activeMenuKey: 'governance-classification',
    kind: 'placeholder',
    features: ['待分类列表', '批量分析', '依据说明'],
  },
  {
    key: 'governance-important-data',
    path: '/governance/important-data',
    title: '重要数据识别',
    breadcrumb: '重要数据识别',
    description: '基于汽车数据分类分级、行业规则和风险矩阵直接展示重要数据识别结论。',
    sectionKey: 'governance',
    sectionLabel: '数据治理与评估',
    activeMenuKey: 'governance-important-data',
    kind: 'placeholder',
    features: ['资产切换', '分类分级基线', '规则路径', '法规依据'],
  },
  {
    key: 'filing-home',
    path: '/filing',
    title: '申报备案首页',
    breadcrumb: '申报备案',
    description: '聚合三类办理事项入口和材料中心导航。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-home',
    kind: 'placeholder',
    features: ['办理事项', '材料中心', '流程入口'],
  },
  {
    key: 'filing-security-assessment',
    path: '/filing/security-assessment',
    title: '安全评估申报',
    breadcrumb: '安全评估申报',
    description: '支持场景表单录入，生成安全评估申报材料包并落入材料中心。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-security-assessment',
    kind: 'placeholder',
    features: ['适用条件', '材料清单', '模板下载'],
  },
  {
    key: 'filing-standard-contract',
    path: '/filing/standard-contract',
    title: '标准合同备案',
    breadcrumb: '标准合同备案',
    description: '支持备案基础信息录入，生成标准合同备案材料和附件说明。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-standard-contract',
    kind: 'placeholder',
    features: ['办理流程', '填报信息', '材料预览'],
  },
  {
    key: 'filing-certification',
    path: '/filing/certification',
    title: '个人信息保护认证',
    breadcrumb: '个人信息保护认证',
    description: '根据治理成熟度和审计准备度生成认证准备材料与补充建议。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-certification',
    kind: 'placeholder',
    features: ['适用场景', '准备情况自测', '认证机构'],
  },
  {
    key: 'filing-materials',
    path: '/filing/materials',
    title: '材料中心',
    breadcrumb: '材料中心',
    description: '支持材料列表筛选、编辑预览、上传元数据和执行完整性检查。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-materials',
    kind: 'placeholder',
    features: ['材料列表', '材料状态', '上传材料文件'],
  },
  {
    key: 'filing-material-detail',
    path: '/filing/materials/:id',
    title: '材料编辑与预览',
    breadcrumb: '材料编辑与预览',
    description: '支持编辑材料标题与说明、上传元数据并同步预览文档。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-materials',
    kind: 'placeholder',
    features: ['结构化输入', '实时预览', '自动保存'],
  },
  {
    key: 'filing-material-check',
    path: '/filing/material-check',
    title: '材料完整性检查',
    breadcrumb: '材料完整性检查',
    description: '支持选择材料执行检查，并输出得分、问题清单和维度图表。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-material-check',
    kind: 'placeholder',
    features: ['检查类型', '问题清单', '完整度评分'],
  },
  {
    key: 'filing-history',
    path: '/filing/history',
    title: '办理记录页',
    breadcrumb: '办理记录',
    description: '展示办理事项状态、完成度和材料入口，并支持按类型与状态筛选。',
    sectionKey: 'filing',
    sectionLabel: '申报备案',
    activeMenuKey: 'filing-history',
    kind: 'placeholder',
    features: ['办理事项', '材料完成度', '提交记录'],
  },
  {
    key: 'security-home',
    path: '/security',
    title: '安全流通首页',
    breadcrumb: '安全流通',
    description: '展示安全能力地图和核心入口。',
    sectionKey: 'security',
    sectionLabel: '安全流通',
    activeMenuKey: 'security-home',
    kind: 'placeholder',
    features: ['能力地图', '快捷入口', '方案总览'],
  },
  {
    key: 'security-solution',
    path: '/security/solution',
    title: '数据安全技术方案',
    breadcrumb: '数据安全技术方案',
    description: '展示脱敏、访问控制、加密传输和日志审计能力方案。',
    sectionKey: 'security',
    sectionLabel: '安全流通',
    activeMenuKey: 'security-solution',
    kind: 'placeholder',
    features: ['数据脱敏', '访问控制', '策略配置面板'],
  },
  {
    key: 'security-transfer',
    path: '/security/transfer',
    title: '跨境传输方案',
    breadcrumb: '跨境传输方案',
    description: '展示专线、网关和可信空间三类传输方案，并支持一键启用。',
    sectionKey: 'security',
    sectionLabel: '安全流通',
    activeMenuKey: 'security-transfer',
    kind: 'placeholder',
    features: ['方案卡片', '传输路径', '启用方案'],
  },
  {
    key: 'security-monitor',
    path: '/security/monitor',
    title: '安全监测页',
    breadcrumb: '安全监测',
    description: '聚合节点吞吐、风险事件和链路趋势，形成统一监测视图。',
    sectionKey: 'security',
    sectionLabel: '安全流通',
    activeMenuKey: 'security-monitor',
    kind: 'placeholder',
    features: ['实时传输量', '风险事件', '节点状态'],
  },
  {
    key: 'security-audit',
    path: '/security/audit',
    title: '审计日志页',
    breadcrumb: '审计日志',
    description: '支持按关键词和风险等级筛选审计日志，并展示主体、对象和结果。',
    sectionKey: 'security',
    sectionLabel: '安全流通',
    activeMenuKey: 'security-audit',
    kind: 'placeholder',
    features: ['操作主体', '来源与目的地', '日志详情'],
  },
  {
    key: 'security-trusted-space',
    path: '/security/trusted-space',
    title: '可信数据空间',
    breadcrumb: '可信数据空间',
    description: '展示参与方、流转路径和隐私计算等可信数据空间能力。',
    sectionKey: 'security',
    sectionLabel: '安全流通',
    activeMenuKey: 'security-trusted-space',
    kind: 'placeholder',
    features: ['参与方', '数据流转图', '隐私计算能力卡片'],
  },
  {
    key: 'services-home',
    path: '/services',
    title: '服务中心首页',
    breadcrumb: '服务中心',
    description: '聚合服务机构、咨询、培训和申请入口。',
    sectionKey: 'services',
    sectionLabel: '服务中心',
    activeMenuKey: 'services-home',
    kind: 'placeholder',
    features: ['专业机构', '专家咨询', '培训课程'],
  },
  {
    key: 'services-providers',
    path: '/services/providers',
    title: '专业机构列表',
    breadcrumb: '专业机构',
    description: '支持按地区、类型和标签筛选专业机构，并展示行业与服务摘要。',
    sectionKey: 'services',
    sectionLabel: '服务中心',
    activeMenuKey: 'services-providers',
    kind: 'placeholder',
    features: ['机构列表', '地区筛选', '详情抽屉'],
  },
  {
    key: 'services-consultation',
    path: '/services/consultation',
    title: '专家咨询页',
    breadcrumb: '专家咨询',
    description: '支持提交咨询问题、指定机构并在平台工作区留存咨询记录。',
    sectionKey: 'services',
    sectionLabel: '服务中心',
    activeMenuKey: 'services-consultation',
    kind: 'placeholder',
    features: ['咨询类型', '问题描述', '历史记录'],
  },
  {
    key: 'services-training',
    path: '/services/training',
    title: '培训课程页',
    breadcrumb: '培训课程',
    description: '展示课程列表、资料下载项和报名操作。',
    sectionKey: 'services',
    sectionLabel: '服务中心',
    activeMenuKey: 'services-training',
    kind: 'placeholder',
    features: ['课程列表', '课程详情', '课程报名'],
  },
  {
    key: 'services-application',
    path: '/services/application',
    title: '服务申请页',
    breadcrumb: '服务申请',
    description: '支持提交服务类型、需求说明和指定机构，并保存申请记录。',
    sectionKey: 'services',
    sectionLabel: '服务中心',
    activeMenuKey: 'services-application',
    kind: 'placeholder',
    features: ['服务类型', '需求说明', '申请记录'],
  },
];

export const quickAccessItems = [
  {
    key: 'search',
    label: '全局搜索',
    path: '/search',
    icon: <SearchOutlined />,
  },
  {
    key: 'reports',
    label: '报告中心',
    path: '/reports',
    icon: <FileSearchOutlined />,
  },
  {
    key: 'country',
    label: '国内法规智库',
    path: '/regulations',
    icon: <BankOutlined />,
  },
];

export const navigationMenuItems: MenuItem[] = primaryNavigation.map((section) => ({
  key: section.key,
  icon: section.icon,
  label: section.label,
  children: section.children?.map((child) => ({
    key: child.key,
    label: child.label,
  })),
}));

const sortedRouteCatalog = [...routeCatalog].sort((left, right) => {
  const leftParamCount = (left.path.match(/:/g) ?? []).length;
  const rightParamCount = (right.path.match(/:/g) ?? []).length;

  if (leftParamCount !== rightParamCount) {
    return leftParamCount - rightParamCount;
  }

  return right.path.length - left.path.length;
});

export const matchRouteMeta = (pathname: string) =>
  sortedRouteCatalog.find((route) =>
    matchPath({ path: route.path, end: true }, pathname),
  );

export const getSectionByKey = (sectionKey: string) =>
  primaryNavigation.find((item) => item.key === sectionKey);
